urls.py
from django.urls import path
from authapp import views
from django.contrib.auth.views import LoginView

app_name = 'auth'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='authapp/login.html'),
         name='login'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('password-change/', views.password_change, name='password_change'),
    path('logout/', views.logout_view, name='logout'),
    path('welcome/', views.welcome, name='welcome'),
]

models.py
from django.db import models

# Create your models here.

forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password'
        ]

views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from authapp.forms import RegisterForm, EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required


# Create your views here.


def welcome(request):
    return HttpResponse('Welcome page renders out')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('auth:welcome')

    context = {'form': RegisterForm()}
    return render(request, 'authapp/register.html', context)


@login_required(login_url='/auth/login')
def profile(request):
    context = {'user': request.user}
    return render(request, 'authapp/profile.html', context)


@login_required(login_url='/auth/login')
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('auth:welcome')

    context = {'form': EditProfileForm(instance=request.user)}
    return render(request, 'authapp/edit_profile.html', context)


@login_required(login_url='/auth/login')
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('auth:welcome')

    context = {'form': PasswordChangeForm(user=request.user)}
    return render(request, 'authapp/password_change_form.html', context)


@login_required(login_url='/auth/login')
def logout_view(request):
    logout(request)
    return redirect('auth:login')

templates/authapp/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
       <div class="container">
           <ul class="navbar-nav">
            {% if not user.is_authenticated %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'auth:login' %}">
                      Login
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth:register' %}">
                      Register
                  </a>
                </li>
            {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth:profile' %}">
                      Profile
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth:logout' %}">
                      Logout
                  </a>
                </li>
            {% endif %}
          </ul>
       </div>
    </nav>

    <div style="margin-top: 30px" class="container">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

templates/authapp/edit_profile.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Profile Form
{% endblock %}

{% block content %}
    <div>
        <h3>Edit Profile Form</h3>

        <div class="row">
            <div class="col-md-6">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <input type="submit" value="Login" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Login Form
{% endblock %}

{% block content %}
    <div>
        <h3>Login Form</h3>

        <div class="row">
            <div class="col-md-6">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <input type="submit" value="Login" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/authapp/password_change_form.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Password Reset Form
{% endblock %}

{% block content %}
    <div>
        <h3>Password Reset Form</h3>

        <div class="row">
            <div class="col-md-6">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <input type="submit" value="Login" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/authapp/profile.html
{% extends 'authapp/base.html' %}

{% block title %}
    Profile Page
{% endblock %}

{% block content %}
    <div>
        <h3>Profile Page</h3>

        <div class="row">
            <div class="col-md-6">
                {% if user.first_name %}
                    <p>{{ user.first_name }}</p>
                {% else  %}
                    <p>Not update yet</p>
                {% endif %}

                {% if user.last_name %}
                    <p>{{ user.last_name }}</p>
                {% else %}
                    <p>Not update yet</p>
                {% endif %}

                <p>{{ user.username }}</p>
                <p>{{ user.email }}</p>

                <a href="{% url 'auth:edit_profile' %}" class="btn btn-primary">
                    Edit Profile
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Registration Form
{% endblock %}

{% block content %}
    <div>
        <h3>Registration Form</h3>

        <div class="row">
            <div class="col-md-6">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <input type="submit" value="Login" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
{% endblock %}